[project]
name = "geotags"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django==5",
    "djangorestframework>=3.16.1",
    "drf-spectacular>=0.29.0",
    "drf-yasg>=1.21.11",
    "psycopg2-binary>=2.9.11",
]
